[[redirects]]
  from = "/collections*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/engines*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/nfts*"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/protocol"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/wallet"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/network"
  to = "/index.html"
  status = 200
